import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Navber from "@/components/Navber/Navber";
import Footer from "@/components/Footer/Footer";
import cartcontextProvider from "@/components/context/context";
import { Toaster } from "react-hot-toast";
import Cartcontextprovider from "@/components/context/context";
import RouteLoader from "@/components/GlabelLoading/RouteLoader";
import Provider from "@/components/Provider/Provider";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
